"""initial storage schema

Revision ID: 46ae4bcc2472
Revises:
Create Date: 2026-07-27 05:45:13.257100
"""

# ruff: noqa: E501  (Alembic-autogenerated DDL: long single-statement create_table/index calls)
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "46ae4bcc2472"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acl_entries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("object_ref", sa.String(), nullable=False),
        sa.Column("subject_principal_id", sa.String(), nullable=False),
        sa.Column("grantee_kind", sa.String(), nullable=False),
        sa.Column("grant_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_acl_object_active",
        "acl_entries",
        ["workspace_id", "object_ref"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "ix_acl_subject_active",
        "acl_entries",
        ["subject_principal_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "agent_bindings",
        sa.Column("agent_principal_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("namespace_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("allowed_tools", sa.JSON(), nullable=False),
        sa.Column("policy_cap", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("agent_principal_id", "workspace_id", "namespace_id", "session_id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_org_ts", "audit_log", ["org_id", "ts"], unique=False)
    op.create_index("ix_audit_ws_ts", "audit_log", ["workspace_id", "ts"], unique=False)
    op.create_table(
        "conflict_records",
        sa.Column("conflict_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("namespace_prefix", sa.String(), nullable=False),
        sa.Column(
            "member_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("predicate_key", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("detected_confidence", sa.Float(), nullable=False),
        sa.Column("proposed_winner_id", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("resolution_kind", sa.String(), nullable=True),
        sa.Column("resolved_winner_id", sa.String(), nullable=True),
        sa.Column("resolution_origin", sa.String(), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column(
            "policy_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("conflict_id"),
    )
    op.create_index(
        "gin_conflict_members",
        "conflict_records",
        ["member_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_conflict_pending", "conflict_records", ["namespace_prefix", "state"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("app_build", sa.String(), nullable=False),
        sa.Column("client_mode", sa.String(), nullable=False),
        sa.Column("privacy_tier", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_seq", sa.BigInteger(), nullable=False),
        sa.Column("last_lamport", sa.BigInteger(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_index("ix_devices_principal", "devices", ["org_id", "principal_id"], unique=False)
    op.create_table(
        "fact_provenance",
        sa.Column("memory_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("namespace_prefix", sa.String(), nullable=False),
        sa.Column("subject_entity_uid", sa.String(), nullable=False),
        sa.Column("predicate", sa.String(), nullable=False),
        sa.Column("object_entity_uid", sa.String(), nullable=True),
        sa.Column("object_value_hash", sa.String(), nullable=True),
        sa.Column("polarity", sa.String(), nullable=False),
        sa.Column("valid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invalid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_at_inferred", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("memory_id"),
    )
    op.create_index(
        "ix_fact_active",
        "fact_provenance",
        ["namespace_prefix", "state"],
        unique=False,
        postgresql_where=sa.text("state = 'active'"),
    )
    op.create_index(
        "ix_fact_conflict",
        "fact_provenance",
        ["namespace_prefix", "subject_entity_uid", "predicate"],
        unique=False,
    )
    op.create_table(
        "grants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("object_ref", sa.String(), nullable=False),
        sa.Column("grantor", sa.String(), nullable=False),
        sa.Column("grantee_principal_id", sa.String(), nullable=False),
        sa.Column("grantee_kind", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("parent_grant_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_grants_grantee_active",
        "grants",
        ["grantee_principal_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "ix_grants_object",
        "grants",
        ["workspace_id", "object_ref"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "ix_grants_parent",
        "grants",
        ["parent_grant_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "memory_provenance",
        sa.Column("memory_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("namespace_prefix", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("artifact_ref", sa.String(), nullable=True),
        sa.Column("provenance_id", sa.String(), nullable=False),
        sa.Column("superseded_by", sa.String(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("memory_id"),
    )
    op.create_index(
        "gin_prov_meta", "memory_provenance", ["meta"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_prov_artifact",
        "memory_provenance",
        ["workspace_id", "artifact_ref"],
        unique=False,
        postgresql_where=sa.text("artifact_ref IS NOT NULL"),
    )
    op.create_index(
        "ix_prov_owner", "memory_provenance", ["org_id", "workspace_id", "owner_id"], unique=False
    )
    op.create_index(
        "ux_prov_chash",
        "memory_provenance",
        ["org_id", "workspace_id", "content_hash"],
        unique=True,
    )
    op.create_table(
        "namespaces",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("owner_principal_id", sa.String(), nullable=False),
        sa.Column("allowed_visibilities", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orgs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("residency_region", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ux_orgs_slug", "orgs", ["slug"], unique=True)
    op.create_table(
        "principals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "private_sync_log",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("origin_device_id", sa.String(), nullable=False),
        sa.Column("op", sa.String(), nullable=False),
        sa.Column("memory_id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("valid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_at_inferred", sa.Boolean(), nullable=False),
        sa.Column("lamport", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provenance_id", sa.String(), nullable=False),
        sa.Column("winner_id", sa.String(), nullable=True),
        sa.Column("loser_id", sa.String(), nullable=True),
        sa.Column("payload_ref", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("org_id", "principal_id", "seq"),
        sa.UniqueConstraint(
            "org_id",
            "principal_id",
            "content_hash",
            "origin_device_id",
            "lamport",
            name="ux_synclog_occurrence",
        ),
    )
    op.create_index(
        "ix_synclog_stream_seq", "private_sync_log", ["org_id", "principal_id", "seq"], unique=False
    )
    op.create_table(
        "provenance_ledger",
        sa.Column("stream_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("memory_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("stream_id", "version"),
    )
    op.create_index(
        "ix_prov_ledger_memory",
        "provenance_ledger",
        ["org_id", "workspace_id", "memory_id"],
        unique=False,
    )
    op.create_table(
        "session_participants",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("session_id", "principal_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("namespace_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trust_ledger_entries",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("actor_principal_id", sa.String(), nullable=False),
        sa.Column("subject_principal_id", sa.String(), nullable=True),
        sa.Column("object_ref", sa.String(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prev_hash", sa.String(), nullable=True),
        sa.Column("entry_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", "seq"),
    )
    op.create_index(
        "ix_trust_object", "trust_ledger_entries", ["workspace_id", "object_ref"], unique=False
    )
    op.create_index(
        "ix_trust_principal",
        "trust_ledger_entries",
        ["workspace_id", "subject_principal_id"],
        unique=False,
    )
    op.create_table(
        "usage_event",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("to_prefix", sa.String(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("deployment_mode", sa.String(), nullable=False),
        sa.Column("dimension", sa.String(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("op", sa.String(), nullable=True),
        sa.Column("tier", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("engine", sa.String(), nullable=True),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("tokens_in", sa.BigInteger(), nullable=True),
        sa.Column("tokens_out", sa.BigInteger(), nullable=True),
        sa.Column("cached_input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("reasoning_tokens", sa.BigInteger(), nullable=True),
        sa.Column("prev_hash", sa.String(), nullable=True),
        sa.Column("row_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("ix_usage_org_occurred", "usage_event", ["org_id", "occurred_at"], unique=False)
    op.create_index(
        "ix_usage_ws_occurred", "usage_event", ["workspace_id", "occurred_at"], unique=False
    )
    op.create_index("ix_usage_ws_seq", "usage_event", ["workspace_id", "seq"], unique=False)
    op.create_table(
        "usage_outbox",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enqueued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("drained_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "usage_rollup",
        sa.Column("bucket_key", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("dimension", sa.String(), nullable=False),
        sa.Column("hour_bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column(
            "qualifiers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_high_water_seq", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("bucket_key"),
    )
    op.create_table(
        "workspace_memberships",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", "principal_id"),
    )
    op.create_index(
        "ix_ws_membership_org", "workspace_memberships", ["org_id", "principal_id"], unique=False
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workspaces_org", "workspaces", ["org_id"], unique=False)
    op.create_index("ux_workspaces_org_slug", "workspaces", ["org_id", "slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux_workspaces_org_slug", table_name="workspaces")
    op.drop_index("ix_workspaces_org", table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index("ix_ws_membership_org", table_name="workspace_memberships")
    op.drop_table("workspace_memberships")
    op.drop_table("usage_rollup")
    op.drop_table("usage_outbox")
    op.drop_index("ix_usage_ws_seq", table_name="usage_event")
    op.drop_index("ix_usage_ws_occurred", table_name="usage_event")
    op.drop_index("ix_usage_org_occurred", table_name="usage_event")
    op.drop_table("usage_event")
    op.drop_index("ix_trust_principal", table_name="trust_ledger_entries")
    op.drop_index("ix_trust_object", table_name="trust_ledger_entries")
    op.drop_table("trust_ledger_entries")
    op.drop_table("sessions")
    op.drop_table("session_participants")
    op.drop_index("ix_prov_ledger_memory", table_name="provenance_ledger")
    op.drop_table("provenance_ledger")
    op.drop_index("ix_synclog_stream_seq", table_name="private_sync_log")
    op.drop_table("private_sync_log")
    op.drop_table("principals")
    op.drop_index("ux_orgs_slug", table_name="orgs")
    op.drop_table("orgs")
    op.drop_table("namespaces")
    op.drop_index("ux_prov_chash", table_name="memory_provenance")
    op.drop_index("ix_prov_owner", table_name="memory_provenance")
    op.drop_index(
        "ix_prov_artifact",
        table_name="memory_provenance",
        postgresql_where=sa.text("artifact_ref IS NOT NULL"),
    )
    op.drop_index("gin_prov_meta", table_name="memory_provenance", postgresql_using="gin")
    op.drop_table("memory_provenance")
    op.drop_index(
        "ix_grants_parent", table_name="grants", postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.drop_index(
        "ix_grants_object", table_name="grants", postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.drop_index(
        "ix_grants_grantee_active",
        table_name="grants",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("grants")
    op.drop_index("ix_fact_conflict", table_name="fact_provenance")
    op.drop_index(
        "ix_fact_active", table_name="fact_provenance", postgresql_where=sa.text("state = 'active'")
    )
    op.drop_table("fact_provenance")
    op.drop_index("ix_devices_principal", table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_conflict_pending", table_name="conflict_records")
    op.drop_index("gin_conflict_members", table_name="conflict_records", postgresql_using="gin")
    op.drop_table("conflict_records")
    op.drop_index("ix_audit_ws_ts", table_name="audit_log")
    op.drop_index("ix_audit_org_ts", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("agent_bindings")
    op.drop_index(
        "ix_acl_subject_active",
        table_name="acl_entries",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index(
        "ix_acl_object_active",
        table_name="acl_entries",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("acl_entries")
    # ### end Alembic commands ###
