"""Domain models — the pydantic-v2 value objects and DTOs (the shared vocabulary).

Built in FULL now (DEV-STANDARDS: "data models are built in FULL now"; schema is hard to change),
ported/pinned from CANONICAL-CONTRACTS.md §1/§5/§7, platform-layer0-spec.md §2/§3, and
storage-schema-rowmapper-spec.md §1. Every public model is re-exported here with an explicit
``__all__`` (mypy ``no_implicit_reexport``).
"""

from mu_contracts.domain.model.agent import (
    AgentFramework,
    AgentIdentity,
    mint_agent_principal_id,
    resolve_subagent_identity,
    subagent_partition_session,
    subagent_write_namespace,
)
from mu_contracts.domain.model.artifact import (
    ArtifactKind,
    ContextArtifact,
    Retention,
    RetentionPolicy,
)
from mu_contracts.domain.model.conflict import (
    ConflictEdgeRow,
    ConflictEdges,
    ConflictRecord,
    ConflictState,
    ResolutionOrigin,
)
from mu_contracts.domain.model.device import (
    ClientMode,
    DeviceEnrollRequest,
    DevicePlatform,
    DeviceRecord,
    DeviceState,
    HostingMode,
    PrivacyTier,
    RevokeReason,
)
from mu_contracts.domain.model.device_sync import PrivateDelta, PrivateSnapshot, SyncOp
from mu_contracts.domain.model.entity import EntityCandidate, EntityResolution
from mu_contracts.domain.model.governance import (
    AclEntry,
    ComposedContext,
    Direction,
    Grant,
    GrantState,
    Permission,
    PrincipalRef,
    PrincipalRefKind,
    ProvenanceAction,
    Revocation,
    Role,
    RoleMembership,
    ShareableRef,
    ShareableType,
    TransferClass,
    TransferState,
)
from mu_contracts.domain.model.health import (
    MemoryHealthEntry,
    MemoryHealthFlag,
    MemoryHealthSummary,
    MemoryHealthView,
)
from mu_contracts.domain.model.lifecycle import (
    JobHandle,
    JobResult,
    JobStatus,
    LifecycleJob,
    LifecycleJobKind,
    UserPrefix,
)
from mu_contracts.domain.model.memory import (
    MemoryItem,
    MemoryKind,
    Namespace,
    Polarity,
    SalienceComponents,
    State,
    Tier,
    Triple,
    Validity,
    Visibility,
)
from mu_contracts.domain.model.model_io import Completion
from mu_contracts.domain.model.notification import (
    ChannelPolicy,
    FrameRef,
    Notification,
    NotificationCategory,
    NotificationKind,
    NotificationPreferences,
    NotificationSeverity,
    NotificationState,
    QuietHours,
)
from mu_contracts.domain.model.persona import PersonaProfile, PersonaSlot, SlotValue
from mu_contracts.domain.model.pin import PinRequest, PinResult
from mu_contracts.domain.model.recall import (
    CallerIdentitySet,
    RecallChannel,
    Scored,
    SparseQuery,
    Vector,
)
from mu_contracts.domain.model.room import MessageKind, ParticipantKind, RoomMessage
from mu_contracts.domain.model.scope import (
    AgentBinding,
    AgentKind,
    ClientScope,
    MembershipStatus,
    OrgMembership,
    Principal,
    PrincipalKind,
    PrincipalRecord,
    PrincipalSource,
    ResolvedPrincipal,
    WorkspaceMembership,
)
from mu_contracts.domain.model.session import (
    NamespaceDefinition,
    SessionDefinition,
    SessionParticipant,
    SessionState,
)
from mu_contracts.domain.model.usage import Usage

__all__ = [
    "AclEntry",
    "AgentBinding",
    "AgentFramework",
    "AgentIdentity",
    "AgentKind",
    "ArtifactKind",
    "CallerIdentitySet",
    "ChannelPolicy",
    "ClientMode",
    "ClientScope",
    "Completion",
    "ComposedContext",
    "ConflictEdgeRow",
    "ConflictEdges",
    "ConflictRecord",
    "ConflictState",
    "ContextArtifact",
    "DeviceEnrollRequest",
    "DevicePlatform",
    "DeviceRecord",
    "DeviceState",
    "Direction",
    "EntityCandidate",
    "EntityResolution",
    "FrameRef",
    "Grant",
    "GrantState",
    "HostingMode",
    "JobHandle",
    "JobResult",
    "JobStatus",
    "LifecycleJob",
    "LifecycleJobKind",
    "MembershipStatus",
    "MemoryHealthEntry",
    "MemoryHealthFlag",
    "MemoryHealthSummary",
    "MemoryHealthView",
    "MemoryItem",
    "MemoryKind",
    "MessageKind",
    "Namespace",
    "NamespaceDefinition",
    "Notification",
    "NotificationCategory",
    "NotificationKind",
    "NotificationPreferences",
    "NotificationSeverity",
    "NotificationState",
    "OrgMembership",
    "ParticipantKind",
    "Permission",
    "PersonaProfile",
    "PersonaSlot",
    "PinRequest",
    "PinResult",
    "Polarity",
    "Principal",
    "PrincipalKind",
    "PrincipalRecord",
    "PrincipalRef",
    "PrincipalRefKind",
    "PrincipalSource",
    "PrivacyTier",
    "PrivateDelta",
    "PrivateSnapshot",
    "ProvenanceAction",
    "QuietHours",
    "RecallChannel",
    "ResolutionOrigin",
    "ResolvedPrincipal",
    "Retention",
    "RetentionPolicy",
    "Revocation",
    "RevokeReason",
    "Role",
    "RoleMembership",
    "RoomMessage",
    "SalienceComponents",
    "Scored",
    "SessionDefinition",
    "SessionParticipant",
    "SessionState",
    "ShareableRef",
    "ShareableType",
    "SlotValue",
    "SparseQuery",
    "State",
    "SyncOp",
    "Tier",
    "TransferClass",
    "TransferState",
    "Triple",
    "Usage",
    "UserPrefix",
    "Validity",
    "Vector",
    "Visibility",
    "WorkspaceMembership",
    "mint_agent_principal_id",
    "resolve_subagent_identity",
    "subagent_partition_session",
    "subagent_write_namespace",
]
