"""The MACHINE-READABLE wire contract — the Phase-0 item this package's ``__init__`` docstring has
been carrying as SCAFFOLD ("the machine-readable OpenAPI + JSON-Schema the TS SDK and community/
conformant servers generate from", ``contracts/__init__.py:11-14``).

**What was missing, and what it cost.** ``PACKAGING-v2.md`` §1.3 puts "the machine-readable
**OpenAPI + JSON-Schema** that the TS SDK and any community/conformant server generate from" in
``contracts/``; ``PACKAGING-v2.md`` §74/§103 and ``mu-local-and-sdk-spec.md`` §C3 both describe
``mu-sdk-js`` as "the TS twin **generated from** ``mu-contracts`` OpenAPI"; and
``api-mcp-surface-spec.md`` §10 / ``api-sdk-mcp-surface-design.md`` §921 require a golden OpenAPI
snapshot that "fails the build if the generated schema drifts". None of that existed: ``git
ls-tree -r HEAD`` found no OpenAPI or JSON-Schema artifact anywhere in the repo, so ``mu-sdk-js``
is in fact HAND-WRITTEN (14 hand-maintained ``.ts`` modules re-declaring the same shapes in zod),
and the "conformant server" story had no machine-readable contract behind it. Two hand-maintained
mirrors of one shape family drift silently; that is the bug this module closes.

**What this module IS.** The single DECLARATIVE statement of the wire surface:

* :data:`WIRE_MODELS` — the named model family that constitutes the wire vocabulary. Every entry
  is an EXISTING pydantic model from this package; nothing here re-declares a shape.
* :data:`WIRE_OPERATIONS` — the REST operations whose request AND response models are both
  canonical ``mu-contracts`` models, with method/path/status/params.
* :data:`UNCONTRACTED_ROUTES` — the routes ``mu-engine-server`` serves that are NOT yet in the
  contract, each with the concrete reason. This list is deliberately EXPLICIT rather than absent:
  ``packages/mu-engine-server/tests/test_wire_contract_routes.py`` asserts the app's real route
  table is exactly ``WIRE_OPERATIONS`` plus ``UNCONTRACTED_ROUTES``, so a new route cannot be added
  without a deliberate decision about whether it is contracted, and a route that becomes
  contractable cannot be quietly left out.
* :func:`build_openapi` / :func:`build_json_schema` — the generator. Pure pydantic
  (``pydantic.json_schema.models_json_schema``); no new dependency, no code generation, no
  hand-written schema text. ``mu-contracts`` stays pydantic-only (``.importlinter``
  ``contracts-imports-nothing-in-project``).

The emitted artifacts are committed under ``mu_contracts/contracts/schema/`` (inside the package,
so they ship in the wheel and any SDK generator can read them from an installed ``mu-contracts``)
and are regenerated by ``mu-core/scripts/wire_contract.py``.

**Why the route inventory is declared here and CHECKED against the app, not read FROM it.**
``mu-contracts`` may not import ``mu_engine_server`` (``.importlinter``:
``contracts-imports-nothing-in-project``), and more importantly the contract is supposed to be the
authority a *third-party* conformant server is measured against — deriving it from our own
``FastAPI`` app would make our implementation definitionally conformant and the contract
meaningless. So the declaration lives here and the app is tested against it.

**Non-goal (named, not hidden): field DEFAULTS are not part of the SDK-parity check.**
``contracts/defaults.py``'s own docstring stages the SDKs' fallback-default wiring as C4, still
open; both SDKs currently carry bare literals (``mu_sdk.models.consolidate.ConsolidateRequest.
limit = 50``, ``mu-sdk-js``'s ``consolidateRequestSchema`` ``.default(50)``) rather than importing
``DEFAULT_CONSOLIDATE_LIMIT``. A parity check that compared defaults would go RED on a
deliberately-staged item and would be disabled within a week. It compares field NAMES,
REQUIRED-ness and JSON type KIND — the three things that make a wire message parse or fail.
"""

from __future__ import annotations

from typing import Any, Final, Literal

from pydantic import BaseModel, ConfigDict, Field
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaMode, models_json_schema

from mu_contracts.contracts.memory import MemoryResponse
from mu_contracts.contracts.recall import RecallChannels, RecallItemView, RecallResult
from mu_contracts.contracts.requests import (
    AddRequest,
    ConsolidateRequest,
    ContextWindowRequest,
    GetRequest,
    MemoryCreateRequest,
    RecallRequest,
)
from mu_contracts.contracts.views import (
    ConsolidateView,
    ContextView,
    MemoryVerbResult,
    MemoryWriteResult,
)
from mu_contracts.domain.model.memory import Namespace

__all__ = [
    "OPENAPI_VERSION",
    "REF_TEMPLATE",
    "SCHEMA_DIALECT",
    "UNCONTRACTED_ROUTES",
    "WIRE_CONTRACT_VERSION",
    "WIRE_MODELS",
    "WIRE_OPERATIONS",
    "ModelRole",
    "UncontractedRoute",
    "WireOperation",
    "WireParam",
    "build_json_schema",
    "build_openapi",
    "wire_model_names",
]

# Bumped by hand whenever a BREAKING change is made to the emitted surface (a removed operation,
# a removed/renamed field, a narrowed type). Additive changes do not bump it — they are still
# caught by the golden-artifact test, which is what forces the deliberate regeneration.
WIRE_CONTRACT_VERSION: Final = "0.1.0"

# OpenAPI 3.1 IS JSON-Schema 2020-12 (that is the whole point of 3.1, and the reason we can emit
# ONE definition family and reference it from both artifacts instead of maintaining a translation).
OPENAPI_VERSION: Final = "3.1.0"
SCHEMA_DIALECT: Final = "https://json-schema.org/draft/2020-12/schema"
REF_TEMPLATE: Final = "#/components/schemas/{model}"

ModelRole = Literal["request", "response", "shared"]


class WireParam(BaseModel):
    """One non-body parameter (path or query) of a :class:`WireOperation`."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(min_length=1)
    location: Literal["path", "query"]
    schema_type: Literal["string", "integer", "number", "boolean"]
    required: bool
    description: str = ""


class WireOperation(BaseModel):
    """One contracted REST operation.

    ``request_model``/``response_model`` name entries of :data:`WIRE_MODELS`. ``request_projected``
    marks the operations whose canonical request model is projected onto path/query params rather
    than sent as a JSON body (``GetRequest``'s own docstring: "``memory_id`` path param,
    ``user``/``session`` as plain query-param function args") — the model is still the contract for
    WHICH fields exist, it just does not appear as a ``requestBody``.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    operation_id: str = Field(min_length=1)
    method: Literal["GET", "POST", "PUT", "DELETE"]
    path: str = Field(pattern=r"^/")
    summary: str = Field(min_length=1)
    request_model: str | None = None
    request_projected: bool = False
    response_model: str = Field(min_length=1)
    success_status: int = Field(ge=200, le=299)
    error_statuses: tuple[int, ...] = ()
    params: tuple[WireParam, ...] = ()


class UncontractedRoute(BaseModel):
    """A route the server serves that the contract does NOT yet cover, plus the concrete reason.

    An entry here is a KNOWN GAP with an owner, not a waiver: the reason names the exact thing that
    has to move for the route to become contractable.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    method: Literal["GET", "POST", "PUT", "DELETE"]
    path: str = Field(pattern=r"^/")
    reason: str = Field(min_length=1)


# --------------------------------------------------------------------------------------
# The wire vocabulary. Every value is an EXISTING model; this table adds a name and a role,
# never a shape.
# --------------------------------------------------------------------------------------
WIRE_MODELS: Final[dict[str, tuple[type[BaseModel], ModelRole]]] = {
    # Requests (canonical bodies — contracts/requests.py, the R0 single-source set).
    "AddRequest": (AddRequest, "request"),
    "ConsolidateRequest": (ConsolidateRequest, "request"),
    "ContextWindowRequest": (ContextWindowRequest, "request"),
    "GetRequest": (GetRequest, "request"),
    "MemoryCreateRequest": (MemoryCreateRequest, "request"),
    "RecallRequest": (RecallRequest, "request"),
    # Responses (canonical return DTOs — contracts/memory.py, .recall, .views).
    "ConsolidateView": (ConsolidateView, "response"),
    "ContextView": (ContextView, "response"),
    "MemoryResponse": (MemoryResponse, "response"),
    "MemoryVerbResult": (MemoryVerbResult, "response"),
    "MemoryWriteResult": (MemoryWriteResult, "response"),
    "RecallItemView": (RecallItemView, "response"),
    "RecallResult": (RecallResult, "response"),
    # Shared — appear on BOTH a request and a response body, so neither role alone describes them.
    "Namespace": (Namespace, "shared"),
    "RecallChannels": (RecallChannels, "shared"),
}


def wire_model_names(role: ModelRole | None = None) -> tuple[str, ...]:
    """The wire model names, optionally filtered by role (``"shared"`` is never filtered out)."""
    if role is None:
        return tuple(WIRE_MODELS)
    return tuple(name for name, (_model, r) in WIRE_MODELS.items() if r == role or r == "shared")


_USER_PARAM: Final = WireParam(
    name="user",
    location="query",
    schema_type="string",
    required=False,
    description="Private-plane η user segment; the server resolves its own default when absent.",
)
_SESSION_PARAM: Final = WireParam(
    name="session",
    location="query",
    schema_type="string",
    required=False,
    description="Private-plane η session segment.",
)


# --------------------------------------------------------------------------------------
# The contracted operations: exactly those whose request AND response are canonical.
# --------------------------------------------------------------------------------------
WIRE_OPERATIONS: Final[tuple[WireOperation, ...]] = (
    WireOperation(
        operation_id="add_memory",
        method="POST",
        path="/memories",
        summary="INGEST one memory (STM durable, deterministic STM->MTM promote).",
        request_model="AddRequest",
        response_model="MemoryWriteResult",
        success_status=201,
        error_statuses=(400, 401, 422),
    ),
    WireOperation(
        operation_id="get_memory",
        method="GET",
        path="/memories/{memory_id}",
        summary="Point-get one memory by id from the caller's partition. 404 on a miss.",
        request_model="GetRequest",
        request_projected=True,
        response_model="MemoryResponse",
        success_status=200,
        error_statuses=(401, 404),
        params=(
            WireParam(
                name="memory_id",
                location="path",
                schema_type="string",
                required=True,
                description="The memory id.",
            ),
            _USER_PARAM,
            _SESSION_PARAM,
        ),
    ),
    WireOperation(
        operation_id="recall_memories",
        method="POST",
        path="/v1/memories/recall",
        summary="Federate-live RANKED recall (STM floor + MTM dense + LTM graph), fused once.",
        request_model="RecallRequest",
        response_model="RecallResult",
        success_status=200,
        error_statuses=(400, 401, 422),
    ),
    WireOperation(
        operation_id="consolidate_memories",
        method="POST",
        path="/v1/memories/consolidate",
        summary="MTM->LTM DISTILL sweep. 409 under a MANAGED namespace (ADR 0031).",
        request_model="ConsolidateRequest",
        response_model="ConsolidateView",
        success_status=200,
        error_statuses=(401, 409, 422),
    ),
    WireOperation(
        operation_id="build_context_window",
        method="POST",
        path="/v1/context/window",
        summary="Deterministic context-window assembly (no LLM synthesis).",
        request_model="ContextWindowRequest",
        response_model="ContextView",
        success_status=200,
        error_statuses=(400, 401, 422),
    ),
)


# --------------------------------------------------------------------------------------
# The known gaps. Each reason names the exact move that would close it.
# --------------------------------------------------------------------------------------
UNCONTRACTED_ROUTES: Final[tuple[UncontractedRoute, ...]] = (
    UncontractedRoute(
        method="POST",
        path="/v1/memories/{memory_id}/promote",
        reason=(
            "response is canonical (MemoryVerbResult) but the request body MemoryVerbRequest is "
            "declared in mu_engine_server.schemas, not in mu-contracts. Contractable as soon as "
            "MemoryVerbRequest is re-homed here and re-exported from schemas.py the way the five "
            "canonical request models already are."
        ),
    ),
    UncontractedRoute(
        method="POST",
        path="/v1/memories/{memory_id}/demote",
        reason="same as .../promote — MemoryVerbRequest is not a mu-contracts model.",
    ),
    UncontractedRoute(
        method="PUT",
        path="/memories/{memory_id}",
        reason=(
            "response is canonical (MemoryVerbResult); the request body UpdateRequest is declared "
            "in mu_engine_server.schemas, not in mu-contracts."
        ),
    ),
    UncontractedRoute(
        method="DELETE",
        path="/memories/{memory_id}",
        reason=(
            "response is canonical (MemoryVerbResult); its user/session query params are declared "
            "as bare function args on the route, with no canonical request model naming the field "
            "set. GetRequest happens to carry the identical fields but naming it here would put "
            "'GetRequest' on a DELETE in the emitted OpenAPI — an invented mapping, not a "
            "contract. Needs a canonical DeleteRequest (or an explicit alias decision)."
        ),
    ),
    UncontractedRoute(
        method="GET",
        path="/profile",
        reason=(
            "response model LifecycleStateView lives in mu_engine.lifecycle.dto — an ENGINE "
            "internal DTO served directly on the wire. Contractable once it is re-homed to "
            "mu-contracts (see the reported delta in this task's report)."
        ),
    ),
    UncontractedRoute(
        method="POST",
        path="/lifecycle/enforce",
        reason=(
            "request body LifecycleEnforceRequest is a mu_engine_server.schemas model; the "
            "response JobHandle IS canonical (mu_contracts.domain.model.lifecycle)."
        ),
    ),
    UncontractedRoute(
        method="GET",
        path="/lifecycle/events",
        reason=(
            "response model ExplainRecord lives in mu_engine.lifecycle.explain — an ENGINE "
            "internal DTO served directly on the wire, same class of leak as GET /profile."
        ),
    ),
)


# --------------------------------------------------------------------------------------
# Generation.
# --------------------------------------------------------------------------------------
# pydantic keys `models_json_schema`'s result by `(type[BaseModel] | type[PydanticDataclass],
# mode)`.
# Every wire model IS a BaseModel, but `PydanticDataclass` is not part of pydantic's public export
# surface (mypy: "does not explicitly export"), so the alias widens the key to `type[Any]` rather
# than importing a private name or silencing the error with a cast.
_SchemaKey = tuple[Any, JsonSchemaMode]


def _definitions() -> tuple[dict[_SchemaKey, str], dict[str, Any]]:
    """Emit ONE shared ``$defs`` family for every wire model, and the key map into it.

    ``models_json_schema`` is the pydantic entry point that resolves shared nested models (e.g.
    ``RecallChannels``, which appears inside both ``RecallRequest`` and ``RecallResult``) to a
    SINGLE definition instead of duplicating it per top-level model. A model is requested in the
    mode its role implies — ``validation`` for a request (what a server must accept),
    ``serialization`` for a response (what a client must be able to read) — and ``shared`` models
    are requested in both, which is exactly how pydantic decides whether one definition suffices
    or the input/output shapes genuinely differ.
    """
    requested: list[tuple[type[BaseModel], JsonSchemaMode]] = []
    for model, role in WIRE_MODELS.values():
        if role in ("request", "shared"):
            requested.append((model, "validation"))
        if role in ("response", "shared"):
            requested.append((model, "serialization"))

    raw_key_map, top = models_json_schema(
        requested,
        ref_template=REF_TEMPLATE,
        title="Memory Universe wire contract",
        schema_generator=GenerateJsonSchema,
    )
    # pydantic hands back ``{(model, mode): {"$ref": "<template-formatted>"}}``; the contract only
    # ever needs the definition KEY, so unwrap once here rather than at every call site.
    key_map = {key: str(ref["$ref"]).rsplit("/", 1)[-1] for key, ref in raw_key_map.items()}
    defs: dict[str, Any] = dict(top.get("$defs", {}))
    return key_map, defs


def _ref_for(key_map: dict[_SchemaKey, str], name: str, mode: JsonSchemaMode) -> str:
    """The ``components/schemas`` key pydantic assigned to ``name`` in ``mode``.

    Fails LOUD (``KeyError``) rather than emitting a dangling ``$ref``: a contract artifact that
    references a schema it does not define is worse than no artifact at all.
    """
    model, _role = WIRE_MODELS[name]
    return key_map[(model, mode)]


def build_json_schema() -> dict[str, Any]:
    """The standalone JSON-Schema artifact: every wire model as a 2020-12 ``$defs`` bundle.

    This is the artifact a non-OpenAPI consumer (a validator, a codegen that speaks JSON-Schema,
    a conformance harness) reads. It carries the SAME definition objects the OpenAPI document's
    ``components.schemas`` carries — one generation, two framings — so the two can never disagree.
    """
    key_map, defs = _definitions()
    roots: dict[str, str] = {}
    for name, (_model, role) in WIRE_MODELS.items():
        if role in ("request", "shared"):
            roots[name if role != "shared" else f"{name}.request"] = _ref_for(
                key_map, name, "validation"
            )
        if role == "response":
            roots[name] = _ref_for(key_map, name, "serialization")
        elif role == "shared":
            roots[f"{name}.response"] = _ref_for(key_map, name, "serialization")

    return {
        "$schema": SCHEMA_DIALECT,
        "$id": (
            "https://schemas.memory-universe.dev/mu-contracts/"
            f"{WIRE_CONTRACT_VERSION}/wire-models.schema.json"
        ),
        "title": "Memory Universe wire models",
        "description": (
            "Machine-readable JSON-Schema for the mu-contracts wire vocabulary "
            "(PACKAGING-v2 §1.3). GENERATED from the pydantic models by "
            "mu-core/scripts/wire_contract.py — do not edit by hand."
        ),
        "x-wire-contract-version": WIRE_CONTRACT_VERSION,
        "x-model-roles": {name: role for name, (_m, role) in WIRE_MODELS.items()},
        "x-schema-key": dict(roots),
        "$defs": defs,
    }


def _operation_object(op: WireOperation, key_map: dict[_SchemaKey, str]) -> dict[str, Any]:
    obj: dict[str, Any] = {
        "operationId": op.operation_id,
        "summary": op.summary,
        "responses": {
            str(op.success_status): {
                "description": "Success.",
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": REF_TEMPLATE.format(
                                model=_ref_for(key_map, op.response_model, "serialization")
                            )
                        }
                    }
                },
            }
        },
    }
    for status in op.error_statuses:
        obj["responses"][str(status)] = {"description": _ERROR_DESCRIPTIONS[status]}

    if op.params:
        obj["parameters"] = [
            {
                "name": p.name,
                "in": p.location,
                "required": p.required,
                "description": p.description,
                "schema": {"type": p.schema_type},
            }
            for p in op.params
        ]

    if op.request_model is not None and not op.request_projected:
        obj["requestBody"] = {
            "required": True,
            "content": {
                "application/json": {
                    "schema": {
                        "$ref": REF_TEMPLATE.format(
                            model=_ref_for(key_map, op.request_model, "validation")
                        )
                    }
                }
            },
        }
    elif op.request_model is not None:
        # Projected: the canonical model still NAMES the field set, it is just carried as
        # path/query params. Recorded as an extension so a generator can still bind the two.
        obj["x-request-model"] = _ref_for(key_map, op.request_model, "validation")
        obj["x-request-projection"] = "path+query"

    return obj


_ERROR_DESCRIPTIONS: Final[dict[int, str]] = {
    400: "Invalid argument (e.g. an unknown tier).",
    401: "Missing or invalid bearer token.",
    404: "Not found.",
    409: "Refused: the namespace is MANAGED and the caller does not own its lifecycle (ADR 0031).",
    422: "Request body failed schema validation.",
}


def build_openapi() -> dict[str, Any]:
    """The OpenAPI 3.1 artifact for the contracted operations.

    Only :data:`WIRE_OPERATIONS` appear as ``paths``; :data:`UNCONTRACTED_ROUTES` are carried in
    the ``x-uncontracted-routes`` extension WITH their reasons, so a reader of the document sees
    the gap instead of inferring that the surface is five routes wide.
    """
    key_map, defs = _definitions()
    paths: dict[str, dict[str, Any]] = {}
    for op in WIRE_OPERATIONS:
        paths.setdefault(op.path, {})[op.method.lower()] = _operation_object(op, key_map)

    return {
        "openapi": OPENAPI_VERSION,
        "jsonSchemaDialect": SCHEMA_DIALECT,
        "info": {
            "title": "Memory Universe wire contract",
            "version": WIRE_CONTRACT_VERSION,
            "license": {"name": "Apache-2.0"},
            "description": (
                "GENERATED from the mu-contracts pydantic models by "
                "mu-core/scripts/wire_contract.py — do not edit by hand. Covers the operations "
                "whose request AND response models are both canonical mu-contracts models; the "
                "remaining mu-engine-server routes are listed under x-uncontracted-routes with "
                "the reason each is not yet contractable."
            ),
        },
        "components": {
            "schemas": defs,
            "securitySchemes": {
                "bearerAuth": {"type": "http", "scheme": "bearer"},
            },
        },
        "security": [{"bearerAuth": []}],
        "paths": paths,
        "x-uncontracted-routes": [
            {"method": r.method, "path": r.path, "reason": r.reason} for r in UNCONTRACTED_ROUTES
        ],
    }
